
services:
  agv:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: ${BUILD_MODE:-deployment}
      args:
        BUILD_DEEPAK: ${BUILD_DEEPAK:-true}
        BUILD_MANASA: ${BUILD_MANASA:-true}
    image: agv:latest
    container_name: agv
    # network_mode: host is required to access native SocketCAN interfaces (e.g., can0) from within the container
    network_mode: host
    privileged: true
    volumes:
      - ../agv_env.bash:/agv_env.bash:ro
      - ../robot_ws/config:/agv_config
