roboteq_driver_node:
  ros__parameters:
    can_interface: "can0"
    feedback_topic: "/drive/feedback"
    diagnostics_topic: "/drive/diagonistics"
    cmd_topic: "/cmd_rpm"

hardware_interface:
  # These are reference parameters for the URDF. The ROS 2 control framework loads them from the URDF <hardware> tag.
  # We define them here as a master reference of what needs to be in the URDF.
  wheel_radius: 0.1
  wheel_base: 0.5
  gear_ratio: 30.0
  ticks_per_rev: 1024.0
  left_joint_name: "left_wheel_joint"
  right_joint_name: "right_wheel_joint"
  feedback_topic: "/drive/feedback"
  cmd_topic: "/cmd_rpm"
